trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    command: buildAndPush
    repository: clajke/devopsazurepipeline
    dockerfile: $(Build.SourcesDirectory)/Dockerfile
    containerRegistry: DockerHubConnection
    tags: |
      1.0
      latest
